<x-layouts::app :title="__('Customer enquiries')">
    <div class="mx-auto w-full max-w-7xl p-4 sm:p-6 lg:p-8">
        <div class="flex flex-col gap-4 border-b border-zinc-200 pb-6 dark:border-zinc-700 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium text-zinc-500 dark:text-zinc-400">Curtains Kenya customer care</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-zinc-900 dark:text-white">Customer enquiries</h1><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">Mark each message once you have replied by email, phone, or WhatsApp.</p></div><a href="{{ route('dashboard') }}" class="text-sm font-medium text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-white">← Dashboard</a></div>
        @if(session('status'))<div class="mt-6 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{{ session('status') }}</div>@endif
        <div class="mt-6 space-y-4">
            @forelse($messages as $message)
                <article class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-3"><h2 class="text-lg font-semibold text-zinc-900 dark:text-white">{{ $message->subject }}</h2><span class="rounded-full px-2.5 py-1 text-xs font-medium {{ $message->responded_at ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300' }}">{{ $message->responded_at ? 'Responded' : 'Awaiting response' }}</span></div><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">From <span class="font-medium text-zinc-700 dark:text-zinc-200">{{ $message->name }}</span> · <a href="mailto:{{ $message->email }}" class="hover:underline">{{ $message->email }}</a>@if($message->phone) · <a href="tel:{{ $message->phone }}" class="hover:underline">{{ $message->phone }}</a>@endif</p><p class="mt-4 whitespace-pre-line text-sm leading-7 text-zinc-700 dark:text-zinc-300">{{ $message->message }}</p><p class="mt-4 text-xs text-zinc-400">Received {{ $message->created_at->format('j M Y, g:i a') }}@if($message->responded_at) · Responded {{ $message->responded_at->format('j M Y, g:i a') }}@endif</p></div><div class="shrink-0">@if($message->responded_at)<form method="POST" action="{{ route('admin.enquiries.new', $message) }}">@csrf @method('PATCH')<button class="rounded-lg border border-zinc-300 px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 dark:border-zinc-600 dark:text-zinc-200 dark:hover:bg-zinc-800">Mark as new</button></form>@else<form method="POST" action="{{ route('admin.enquiries.responded', $message) }}">@csrf @method('PATCH')<button class="rounded-lg bg-zinc-900 px-3 py-2 text-sm font-medium text-white hover:bg-zinc-700 dark:bg-white dark:text-zinc-900">Mark responded</button></form>@endif</div></div></article>
            @empty
                <div class="rounded-xl border border-zinc-200 bg-white px-6 py-16 text-center dark:border-zinc-700 dark:bg-zinc-900"><h2 class="text-lg font-semibold text-zinc-900 dark:text-white">No enquiries yet</h2><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">New messages submitted through the Contact page will appear here.</p></div>
            @endforelse
        </div>
        @if($messages->hasPages())<div class="mt-6">{{ $messages->links() }}</div>@endif
    </div>
</x-layouts::app>
