<form method="POST" action="{{ $post ? route('admin.blog.posts.update', $post) : route('admin.blog.posts.store') }}" enctype="multipart/form-data" class="mt-6 space-y-6">
    @csrf @if($post) @method('PUT') @endif
    <div class="space-y-5 rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900">
        <div><label for="title" class="text-sm font-medium dark:text-white">Article title</label><input id="title" name="title" required value="{{ old('title', $post?->title) }}" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800">@error('title')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="slug" class="text-sm font-medium dark:text-white">URL slug (optional)</label><input id="slug" name="slug" value="{{ old('slug', $post?->slug) }}" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800">@error('slug')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="blog_category_id" class="text-sm font-medium dark:text-white">Blog category</label><select id="blog_category_id" name="blog_category_id" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"><option value="">Uncategorised</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('blog_category_id', $post?->blog_category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div></div>
        <div><label for="excerpt" class="text-sm font-medium dark:text-white">Short introduction</label><textarea id="excerpt" name="excerpt" rows="3" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800">{{ old('excerpt', $post?->excerpt) }}</textarea></div>
        <div><label for="content" class="text-sm font-medium dark:text-white">Article content</label><p class="mt-1 text-xs text-zinc-500">Select text and use the toolbar to add SEO-friendly headings, emphasis, lists and links. HTML is stripped for visitor safety.</p><div class="mt-2 flex flex-wrap gap-1 rounded-t-lg border border-b-0 border-zinc-300 bg-zinc-50 p-2 dark:border-zinc-700 dark:bg-zinc-800" role="toolbar" aria-label="Article formatting"><button type="button" data-markdown-before="## " data-markdown-after="" class="rounded border border-zinc-300 bg-white px-2 py-1 text-xs font-semibold dark:border-zinc-600 dark:bg-zinc-900">H2</button><button type="button" data-markdown-before="### " data-markdown-after="" class="rounded border border-zinc-300 bg-white px-2 py-1 text-xs font-semibold dark:border-zinc-600 dark:bg-zinc-900">H3</button><button type="button" data-markdown-before="**" data-markdown-after="**" class="rounded border border-zinc-300 bg-white px-2 py-1 text-xs font-bold dark:border-zinc-600 dark:bg-zinc-900">Bold</button><button type="button" data-markdown-before="*" data-markdown-after="*" class="rounded border border-zinc-300 bg-white px-2 py-1 text-xs italic dark:border-zinc-600 dark:bg-zinc-900">Italic</button><button type="button" data-markdown-before="- " data-markdown-after="" class="rounded border border-zinc-300 bg-white px-2 py-1 text-xs dark:border-zinc-600 dark:bg-zinc-900">List</button><button type="button" data-markdown-before="[" data-markdown-after="](https://)" class="rounded border border-zinc-300 bg-white px-2 py-1 text-xs dark:border-zinc-600 dark:bg-zinc-900">Link</button></div><textarea id="content" name="content" required rows="18" class="w-full rounded-b-lg border-zinc-300 font-mono text-sm dark:border-zinc-700 dark:bg-zinc-800">{{ old('content', $post?->content) }}</textarea>@error('content')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="featured_image" class="text-sm font-medium dark:text-white">Featured image</label>@if($post?->featured_image)<img src="{{ $post->imageUrl() }}" alt="{{ $post->featured_image_alt }}" class="mt-2 h-28 w-44 rounded object-cover">@endif<input id="featured_image" name="featured_image" type="file" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full text-sm"></div><div><label for="featured_image_alt" class="text-sm font-medium dark:text-white">Image alt text</label><input id="featured_image_alt" name="featured_image_alt" value="{{ old('featured_image_alt', $post?->featured_image_alt) }}" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div></div>
        <div class="grid gap-5 sm:grid-cols-2"><div><label for="status" class="text-sm font-medium dark:text-white">Publication</label><select id="status" name="status" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"><option value="draft" @selected(old('status', $post?->status ?? 'draft') === 'draft')>Draft</option><option value="published" @selected(old('status', $post?->status) === 'published')>Published</option></select></div><div><label for="published_at" class="text-sm font-medium dark:text-white">Publish date &amp; time</label><input id="published_at" type="datetime-local" name="published_at" value="{{ old('published_at', $post?->published_at?->format('Y-m-d\\TH:i')) }}" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div></div>
    </div>
    <details open class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><summary class="cursor-pointer font-medium dark:text-white">SEO and social sharing details</summary><p class="mt-2 text-xs text-zinc-500">These fields control how the article appears in Google results and when shared on social media.</p><div class="mt-5 grid gap-5"><div><label class="text-sm font-medium dark:text-white">SEO title</label><input name="seo_title" maxlength="255" value="{{ old('seo_title', $post?->seo_title) }}" placeholder="A clear search title, ideally 50–60 characters" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div><div><label class="text-sm font-medium dark:text-white">Meta description</label><textarea name="meta_description" maxlength="180" rows="2" placeholder="Summarise the article for search results, ideally 140–160 characters" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800">{{ old('meta_description', $post?->meta_description) }}</textarea></div><div><label class="text-sm font-medium dark:text-white">Keywords / phrases</label><input name="seo_keywords" value="{{ old('seo_keywords', $post?->seo_keywords) }}" placeholder="curtains kenya, blackout curtains, curtain measurements" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div><div><label class="text-sm font-medium dark:text-white">Custom canonical URL</label><input type="url" name="canonical_url" value="{{ old('canonical_url', $post?->canonical_url) }}" placeholder="Leave empty to use the article URL" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-medium dark:text-white">Open Graph title</label><input name="og_title" maxlength="255" value="{{ old('og_title', $post?->og_title) }}" placeholder="Title shown on social media" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div><div><label class="text-sm font-medium dark:text-white">Open Graph image URL</label><input type="url" name="og_image" value="{{ old('og_image', $post?->og_image) }}" placeholder="Leave empty to use the featured image" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div></div><div><label class="text-sm font-medium dark:text-white">Open Graph description</label><textarea name="og_description" maxlength="180" rows="2" placeholder="Description shown when the article is shared" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800">{{ old('og_description', $post?->og_description) }}</textarea></div><label class="flex gap-2 text-sm dark:text-white"><input type="checkbox" value="1" name="noindex" @checked(old('noindex', $post?->noindex))> Prevent search indexing for this article</label></div></details>
    @php($faqValues = old('faqs', $post?->faqs ?? []))
    <details open class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900">
        <summary class="cursor-pointer font-medium dark:text-white">Frequently asked questions (SEO)</summary>
        <p class="mt-2 text-xs text-zinc-500">Add concise questions readers search for. Completed pairs appear on the article and generate FAQ structured data for search engines.</p>
        <div class="mt-5 grid gap-5">
            @for($faqIndex = 0; $faqIndex < 6; $faqIndex++)
                <fieldset class="rounded-lg border border-zinc-200 p-4 dark:border-zinc-700">
                    <legend class="px-2 text-xs font-semibold tracking-wide text-zinc-500 uppercase">Question {{ $faqIndex + 1 }}</legend>
                    <div class="grid gap-4">
                        <div><label for="faq-question-{{ $faqIndex }}" class="text-sm font-medium dark:text-white">Question</label><input id="faq-question-{{ $faqIndex }}" name="faqs[{{ $faqIndex }}][question]" maxlength="255" value="{{ $faqValues[$faqIndex]['question'] ?? '' }}" placeholder="What would a customer search for?" class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800"></div>
                        <div><label for="faq-answer-{{ $faqIndex }}" class="text-sm font-medium dark:text-white">Answer</label><textarea id="faq-answer-{{ $faqIndex }}" name="faqs[{{ $faqIndex }}][answer]" maxlength="2000" rows="3" placeholder="Give a direct, useful answer." class="mt-2 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-800">{{ $faqValues[$faqIndex]['answer'] ?? '' }}</textarea></div>
                    </div>
                </fieldset>
            @endfor
        </div>
        @error('faqs.*.question')<p class="mt-3 text-sm text-red-600">{{ $message }}</p>@enderror
        @error('faqs.*.answer')<p class="mt-3 text-sm text-red-600">{{ $message }}</p>@enderror
    </details>
    <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><summary class="cursor-pointer font-medium dark:text-white">Related content</summary><div class="mt-5 grid gap-6 sm:grid-cols-3"><div><p class="text-sm font-medium dark:text-white">Tags</p><div class="mt-2 max-h-44 space-y-2 overflow-auto">@foreach($tags as $tag)<label class="flex gap-2 text-sm"><input type="checkbox" name="tag_ids[]" value="{{ $tag->id }}" @checked(in_array($tag->id, old('tag_ids', $post?->tags->pluck('id')->all() ?? [])))> {{ $tag->name }}</label>@endforeach</div></div><div><p class="text-sm font-medium dark:text-white">Related products</p><div class="mt-2 max-h-44 space-y-2 overflow-auto">@foreach($products as $product)<label class="flex gap-2 text-sm"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" @checked(in_array($product->id, old('product_ids', $post?->products->pluck('id')->all() ?? [])))> {{ $product->name }}</label>@endforeach</div></div><div><p class="text-sm font-medium dark:text-white">Related articles</p><div class="mt-2 max-h-44 space-y-2 overflow-auto">@foreach($relatedPosts as $relatedPost)<label class="flex gap-2 text-sm"><input type="checkbox" name="related_post_ids[]" value="{{ $relatedPost->id }}" @checked(in_array($relatedPost->id, old('related_post_ids', $post?->relatedPosts->pluck('id')->all() ?? [])))> {{ $relatedPost->title }}</label>@endforeach</div></div></div></details>
    <div class="flex justify-between"><a href="{{ route('admin.blog.posts.index') }}" class="rounded-lg px-4 py-2 text-sm">Cancel</a><div class="flex gap-3">@if($post)<button form="delete-post" type="submit" class="rounded-lg px-4 py-2 text-sm text-red-700">Delete</button>@endif<button class="rounded-lg bg-zinc-900 px-5 py-2.5 text-sm font-medium text-white dark:bg-white dark:text-zinc-900">Save article</button></div></div>
</form>
@if($post)<form id="delete-post" method="POST" action="{{ route('admin.blog.posts.destroy', $post) }}">@csrf @method('DELETE')</form>@endif
<script>
    document.querySelectorAll('[data-markdown-before]').forEach((button) => {
        button.addEventListener('click', () => {
            const editor = document.getElementById('content');
            const before = button.dataset.markdownBefore;
            const after = button.dataset.markdownAfter;
            const selectedText = editor.value.slice(editor.selectionStart, editor.selectionEnd) || 'Text';
            const replacement = `${before}${selectedText}${after}`;

            editor.setRangeText(replacement, editor.selectionStart, editor.selectionEnd, 'select');
            editor.focus();
        });
    });
</script>
