<x-layouts::app :title="__('System administrators')">
    <div class="mx-auto w-full max-w-7xl p-4 sm:p-6 lg:p-8">
        <div class="flex flex-col gap-4 border-b border-zinc-200 pb-6 dark:border-zinc-700 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium text-zinc-500 dark:text-zinc-400">Curtains Kenya access control</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-zinc-900 dark:text-white">System administrators</h1><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">Create staff accounts and give each person access only to the work they handle.</p></div><a href="{{ route('dashboard') }}" class="text-sm font-medium text-zinc-600 hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-white">← Dashboard</a></div>
        @if(session('status'))<div class="mt-6 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300">{{ $errors->first() }}</div>@endif
        <div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
            <section class="overflow-hidden rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-zinc-200 text-left text-sm dark:divide-zinc-700"><thead class="bg-zinc-50 text-xs font-medium tracking-wide text-zinc-500 uppercase dark:bg-zinc-800/60 dark:text-zinc-400"><tr><th class="px-5 py-3">Administrator</th><th class="px-5 py-3">Role</th><th class="px-5 py-3 text-right">Save</th></tr></thead><tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">@foreach($users as $user)<tr><td class="px-5 py-4"><p class="font-medium text-zinc-900 dark:text-white">{{ $user->name }}</p><p class="mt-0.5 text-xs text-zinc-500">{{ $user->email }}</p></td><td class="px-5 py-4"><form id="role-{{ $user->id }}" method="POST" action="{{ route('admin.users.update', $user) }}">@csrf @method('PATCH')<label class="sr-only" for="role-select-{{ $user->id }}">Role for {{ $user->name }}</label><select id="role-select-{{ $user->id }}" name="role" class="rounded-lg border-zinc-300 text-sm dark:border-zinc-600 dark:bg-zinc-800 dark:text-white">@foreach($roles as $value => $label)<option value="{{ $value }}" @selected($user->role === $value)>{{ $label }}</option>@endforeach</select></form></td><td class="px-5 py-4 text-right"><button form="role-{{ $user->id }}" class="rounded-lg border border-zinc-300 px-3 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 dark:border-zinc-600 dark:text-zinc-200 dark:hover:bg-zinc-800">Save role</button></td></tr>@endforeach</tbody></table></div>@if($users->hasPages())<div class="border-t border-zinc-200 px-5 py-4 dark:border-zinc-700">{{ $users->links() }}</div>@endif</section>
            <aside class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><h2 class="text-base font-semibold text-zinc-900 dark:text-white">Add administrator</h2><form method="POST" action="{{ route('admin.users.store') }}" class="mt-5 space-y-4">@csrf<label class="block text-sm font-medium text-zinc-700 dark:text-zinc-200">Name<input name="name" value="{{ old('name') }}" required class="mt-1.5 w-full rounded-lg border-zinc-300 px-3 py-2 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white"></label><label class="block text-sm font-medium text-zinc-700 dark:text-zinc-200">Email<input name="email" type="email" value="{{ old('email') }}" required class="mt-1.5 w-full rounded-lg border-zinc-300 px-3 py-2 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white"></label><label class="block text-sm font-medium text-zinc-700 dark:text-zinc-200">Role<select name="role" class="mt-1.5 w-full rounded-lg border-zinc-300 px-3 py-2 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white">@foreach($roles as $value => $label)<option value="{{ $value }}" @selected(old('role') === $value)>{{ $label }}</option>@endforeach</select></label><label class="block text-sm font-medium text-zinc-700 dark:text-zinc-200">Temporary password<input name="password" type="password" required class="mt-1.5 w-full rounded-lg border-zinc-300 px-3 py-2 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white"></label><label class="block text-sm font-medium text-zinc-700 dark:text-zinc-200">Confirm password<input name="password_confirmation" type="password" required class="mt-1.5 w-full rounded-lg border-zinc-300 px-3 py-2 dark:border-zinc-600 dark:bg-zinc-800 dark:text-white"></label><button class="w-full rounded-lg bg-zinc-900 px-4 py-2.5 text-sm font-medium text-white hover:bg-zinc-700 dark:bg-white dark:text-zinc-900">Create administrator</button></form><div class="mt-6 border-t border-zinc-200 pt-5 text-xs leading-5 text-zinc-500 dark:border-zinc-700 dark:text-zinc-400"><p><strong>Orders Manager:</strong> orders only.</p><p class="mt-2"><strong>Customer Service:</strong> customer enquiries only.</p><p class="mt-2"><strong>Catalogue Manager:</strong> products, categories, and stock.</p><p class="mt-2"><strong>Content Manager:</strong> blog and story content.</p></div></aside>
        </div>
    </div>
</x-layouts::app>
