@extends('layouts.public')

@section('title', 'Curtains Kenya Journal | Home décor guides in Kenya')
@section('description', 'Practical guides on curtains, blinds, bedding, fabrics and home décor for beautifully lived-in Kenyan homes.')

@section('content')
<section class="bg-ck-cream py-14 sm:py-20"><div class="ck-container"><p class="text-xs font-medium tracking-[0.18em] text-ck-brown uppercase">Curtains Kenya Journal</p><h1 class="mt-4 max-w-3xl font-serif text-4xl leading-tight sm:text-6xl">Ideas for a home that feels beautifully yours.</h1><p class="mt-5 max-w-2xl text-base leading-7 text-ck-muted">Thoughtful guides on curtains, blinds, bedding and the details that make a Kenyan home feel complete.</p><form action="{{ route('blog.index') }}" class="mt-8 flex max-w-xl gap-2"><label for="q" class="sr-only">Search the Journal</label><input id="q" name="q" value="{{ $search }}" placeholder="Search guides and ideas" class="min-w-0 flex-1 rounded-lg border-black/15 bg-white px-4 py-3 text-sm focus:border-ck-brown focus:ring-ck-brown"><button class="rounded-lg bg-ck-dark px-5 py-3 text-sm font-medium text-white">Search</button></form></div></section>
<section class="ck-container py-12 sm:py-16">
    <nav aria-label="Blog categories" class="flex flex-wrap gap-2">@foreach ($categories as $category)<a href="{{ route('blog.category', $category) }}" class="rounded-full border border-black/10 px-4 py-2 text-sm hover:border-ck-brown hover:text-ck-brown">{{ $category->name }} <span class="text-ck-muted">{{ $category->posts_count }}</span></a>@endforeach</nav>
    @if ($featuredPost)<div class="mt-10 grid overflow-hidden rounded-2xl bg-ck-dark text-white md:grid-cols-2"><a href="{{ route('blog.show', $featuredPost) }}" class="aspect-[16/10] bg-black/10">@if($featuredPost->featured_image)<img src="{{ asset('storage/'.$featuredPost->featured_image) }}" alt="{{ $featuredPost->featured_image_alt }}" class="size-full object-cover" width="900" height="560">@endif</a><div class="flex flex-col justify-center p-8 sm:p-12"><p class="text-xs tracking-[0.16em] text-white/60 uppercase">Latest guide · {{ $featuredPost->reading_time }} min read</p><h2 class="mt-4 font-serif text-3xl sm:text-4xl"><a href="{{ route('blog.show', $featuredPost) }}">{{ $featuredPost->title }}</a></h2><p class="mt-4 leading-7 text-white/70">{{ $featuredPost->excerpt }}</p><a href="{{ route('blog.show', $featuredPost) }}" class="mt-6 text-sm font-medium underline underline-offset-4">Read the guide</a></div></div>@endif
    <div class="mt-12 flex items-end justify-between gap-4"><div><p class="text-xs font-medium tracking-[0.16em] text-ck-brown uppercase">{{ $search ? 'Search results' : 'Latest articles' }}</p><h2 class="mt-2 font-serif text-3xl">{{ $search ? 'Results for “'.$search.'”' : 'Fresh inspiration' }}</h2></div></div>
    <div class="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">@forelse($posts as $post) @include('blog._card') @empty <p class="col-span-full rounded-xl bg-ck-cream p-8 text-ck-muted">No articles matched your search. Try a different phrase.</p> @endforelse</div>
    @if($posts->hasPages())<div class="mt-10">{{ $posts->links() }}</div>@endif
    @if($tags->isNotEmpty())<div class="mt-14 border-t border-black/10 pt-8"><h2 class="font-serif text-2xl">Popular topics</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($tags as $tag)<a href="{{ route('blog.tag', $tag) }}" class="rounded-full bg-ck-cream px-4 py-2 text-sm hover:text-ck-brown">#{{ $tag->name }}</a>@endforeach</div></div>@endif
</section>
@endsection
