@extends('layouts.public')

@section('title', $post->seoTitle())
@section('description', $post->seoDescription())
@section('canonical', $post->canonicalUrl())
@section('og_type', 'article')
@section('og_title', $post->og_title ?: $post->seoTitle())
@section('og_description', $post->og_description ?: $post->seoDescription())
@if($post->og_image ?: $post->imageUrl()) @section('og_image', $post->og_image ?: $post->imageUrl()) @endif
@section('robots', $post->noindex ? 'noindex,follow' : 'index,follow')
@section('structured_data')
<script type="application/ld+json">{{ json_encode($articleSchema, JSON_UNESCAPED_SLASHES) }}</script>
<script type="application/ld+json">{{ json_encode($breadcrumbSchema, JSON_UNESCAPED_SLASHES) }}</script>
@endsection

@section('content')
<article>
    <header class="bg-ck-cream py-10 sm:py-16"><div class="ck-container max-w-4xl"><nav aria-label="Breadcrumb" class="text-sm text-ck-muted"><a href="{{ route('home') }}" class="hover:text-ck-brown">Home</a><span class="px-2">/</span><a href="{{ route('blog.index') }}" class="hover:text-ck-brown">Journal</a>@if($post->category)<span class="px-2">/</span><a href="{{ route('blog.category', $post->category) }}" class="hover:text-ck-brown">{{ $post->category->name }}</a>@endif</nav><p class="mt-8 text-xs font-medium tracking-[0.17em] text-ck-brown uppercase">{{ $post->category?->name ?? 'Home inspiration' }}</p><h1 class="mt-4 font-serif text-4xl leading-tight sm:text-6xl">{{ $post->title }}</h1><div class="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-ck-muted"><span>By {{ $post->author->name }}</span><span>{{ $post->published_at->format('j F Y') }}</span><span>{{ $post->reading_time }} minute read</span>@if($post->updated_at->gt($post->published_at))<span>Updated {{ $post->updated_at->format('j M Y') }}</span>@endif</div></div></header>
    @if($post->featured_image)<div class="ck-container max-w-6xl py-8 sm:py-12"><img src="{{ asset('storage/'.$post->featured_image) }}" alt="{{ $post->featured_image_alt }}" class="aspect-[16/8] w-full rounded-2xl object-cover" width="1200" height="600"></div>@endif
    <div class="ck-container grid max-w-6xl gap-12 pb-16 lg:grid-cols-[minmax(0,1fr)_15rem]"><div class="mx-auto w-full max-w-3xl">@if($post->excerpt)<p class="border-l-2 border-ck-brown pl-5 font-serif text-xl leading-8 text-ck-dark sm:text-2xl">{{ $post->excerpt }}</p>@endif<div class="prose prose-zinc mt-9 max-w-none prose-headings:font-serif prose-headings:font-normal prose-a:text-ck-brown prose-a:underline prose-img:rounded-xl">{!! \Illuminate\Support\Str::markdown($post->content, ['html_input' => 'strip', 'allow_unsafe_links' => false]) !!}</div><div class="mt-10 border-t border-black/10 pt-6"><p class="text-xs font-medium tracking-[0.15em] text-ck-brown uppercase">Share this guide</p><div class="mt-3 flex flex-wrap gap-3 text-sm"><a class="underline underline-offset-4" target="_blank" rel="noopener" href="https://wa.me/?text={{ urlencode($post->title.' '.$post->canonicalUrl()) }}">WhatsApp</a><a class="underline underline-offset-4" target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u={{ urlencode($post->canonicalUrl()) }}">Facebook</a><a class="underline underline-offset-4" target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?url={{ urlencode($post->canonicalUrl()) }}&text={{ urlencode($post->title) }}">X</a><button type="button" class="underline underline-offset-4" onclick="navigator.clipboard.writeText('{{ $post->canonicalUrl() }}')">Copy link</button></div></div></div>
        <aside class="space-y-5 lg:pt-2"><div class="rounded-xl bg-ck-cream p-5"><h2 class="font-serif text-xl">Need help choosing?</h2><p class="mt-2 text-sm leading-6 text-ck-muted">Talk to Curtains Kenya about the right option for your space.</p><a href="{{ route('contact') }}" class="mt-4 inline-block text-sm font-medium underline underline-offset-4">Contact us</a></div>@if($post->tags->isNotEmpty())<div><h2 class="text-xs font-medium tracking-[0.15em] text-ck-brown uppercase">Topics</h2><div class="mt-3 flex flex-wrap gap-2">@foreach($post->tags as $tag)<a href="{{ route('blog.tag', $tag) }}" class="rounded-full border border-black/10 px-3 py-1.5 text-xs hover:text-ck-brown">#{{ $tag->name }}</a>@endforeach</div></div>@endif</aside>
    </div>
</article>
@if($post->products->isNotEmpty())<section class="bg-ck-cream py-14"><div class="ck-container"><p class="text-xs font-medium tracking-[0.15em] text-ck-brown uppercase">Shop the guide</p><h2 class="mt-2 font-serif text-3xl">Related products</h2><div class="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($post->products as $product)<a href="{{ route('products.show', $product) }}" class="rounded-xl bg-white p-4 shadow-sm hover:-translate-y-0.5">@if($product->images->first())<img src="{{ asset('storage/'.$product->images->first()->image_path) }}" alt="{{ $product->images->first()->alt_text ?: $product->name }}" class="aspect-square w-full rounded-lg object-cover" loading="lazy">@endif<h3 class="mt-3 font-medium">{{ $product->name }}</h3><p class="mt-1 text-sm text-ck-muted">View product →</p></a>@endforeach</div></div></section>@endif
@if($relatedPosts->isNotEmpty())<section class="ck-container py-14"><p class="text-xs font-medium tracking-[0.15em] text-ck-brown uppercase">Keep reading</p><h2 class="mt-2 font-serif text-3xl">Related articles</h2><div class="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">@foreach($relatedPosts as $post) @include('blog._card') @endforeach</div></section>@endif
@endsection
